- name: install docker community edition
  hosts: localhost 
  become: true
  tasks:
    - name: install ca-certificates
      ansible.builtin.apt:
        name: ca-certificates
    - name: install curl
      ansible.builtin.apt:
        name: curl
    - name: install gnupg
      ansible.builtin.apt:
        name: gnupg
    - name: get docker url 
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
    - name: Set DPKG architecture
      ansible.builtin.set_fact:
        dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
    
    - debug:
        msg: "{{ dpkg_arch }}"

    - name: add docker repository 
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: true
    - name: install docker packages
      ansible.builtin.apt:
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        update_cache: yes
