- name: clone packer nvim repository
  hosts: localhost 
  tasks:
    - name: clone repository
      git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: /home/wasikama/.local/share/nvim/site/pack/packer/start/packer.nvim
        clone: true
        depth: 1
