- name: install vscode
  hosts: localhost 
  become: true
  tasks:
    - name: install wget
      apt:
        name: wget
    - name: install gpg
      apt:
        name: gpg
    - name: get vscode url 
      get_url:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        dest: /etc/apt/keyrings/packages.microsoft.asc
        mode: '0644'
        force: true

    - name: add vscode repository 
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main"
        state: present
        filename: vscode
        update_cache: true
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
    - name: install vscode
      apt:
        name: code
        update_cache: yes
